[package]
name = "tankgame_lib"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[lib]
name = "tankgame_lib"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy_vello = { path = "../../", features = ["particles"]}
bevy = { workspace = true }
wasm-bindgen = "0.2.65"
serde_json = { version = "1.0.137", default-features = false, features = ["alloc"] }
bevy_hanabi = { path = "../../../bevy_hanabi", features = ["2d"] }
particle_lib = {path = "../particles_lib"}