[workspace]
resolver = "2"
members = ["demo"]

[workspace.package]
edition = "2021"
version = "0.3.6"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vectorgameexperts/bevy-vello"

[workspace.dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", version = "0.12.0-dev", default-features = true }

[package]
name = "bevy-vello"
description = "Render Lottie and SVG assets in Bevy with Vello"
authors = [
  "Sebastian Hamel <sebjfk@gmail.com>",
  "Spencer C. Imbleau <spencer@imbleau.com>",
]
keywords = ["gamedev", "graphics"]
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy = { workspace = true }
vello = { git = "https://github.com/linebender/vello", rev = "b5e3ae586846c8b9c7ad9b4830d8035a807eb15f" }
vello-svg = { git = "https://github.com/vectorgameexperts/vello-svg", branch = "bevy-0.12-dev" }
vellottie = { git = "https://github.com/vectorgameexperts/vellottie", branch = "bevy-0.12-dev" }
flate2 = "1.0"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

# These settings are to get the WASM blob smaller for the demo.
[profile.release.package."demo"]
codegen-units = 1
opt-level = 'z'
