[package]
name = "bevy-vello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy = { git = "https://github.com/mockersf/bevy", rev = "ec10befeed2195a3e79d46e4567e7e88a0003eb1", default-features = false, features = [
    "bevy_winit","png","bevy_asset","bevy_core_pipeline","bevy_sprite", "bevy_gizmos"
] }
vello = { git = "https://github.com/linebender/vello", rev = "299b47ea064ec3132e294acd9cf243eea7d9ee51" }
vello_svg = { git = "https://github.com/linebender/vello", rev = "299b47ea064ec3132e294acd9cf243eea7d9ee51" }
velato = { git = "https://github.com/vectorgameexperts/velato", rev = "1ca75b131aaed514451f3caef2f67f698ae46b65" }
lyon_geom = "1.0"
lyon_tessellation = "1.0"
lyon_path = "1.0"
svgtypes = "0.9"
copyless = "0.1"
roxmltree = "0.13"
bevy_prototype_debug_lines = "0.10"
