[package]
name = "collision_detection"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ron = "0.8"
#particle won't work with multi-threaded
bevy = { workspace = true}

bevy_vello = { path = "../../"}
bevy_egui = "0.33.0"
nalgebra = "0.33.0"
