[package]
name = "tankgame_bin"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy_vello = { path = "../../", features = ["particles"] }
bevy = { workspace = true }
tankgame_lib = {path = "../../example_libs/tankgame_lib"}
avian2d = "0.1.2"
seldom_state = "0.11"