name: CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v3

    - name: Setup | Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy,fmt

    - name: Build | Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings

    - name: Build | Rustfmt
      run: cargo fmt --all -- --check

  check:
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v3

    - name: Setup | Toolchain (clippy)
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy,fmt

    - name: Build | Check
      run: cargo check --all

  test:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v3

    - name: Setup | Toolchain (clippy)
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy,fmt

    - name: Build | Test
      run: cargo test --all
